added installer for docker 20.10.8

diff --git a/pkg/20.10.8/20.10.8.diff b/pkg/20.10.8/20.10.8.diff
--- a/pkg/20.10.8/20.10.8.diff
+++ b/pkg/20.10.8/20.10.8.diff
@@ -1,8 +1,8 @@
---- 20.10.8.orig.sh	2021-08-16 16:24:35.717603724 +0530
-+++ 20.10.8.sh	2021-08-16 16:52:59.153773104 +0530
+--- 20.10.8.orig.sh	2021-11-24 11:22:22.516724049 +0530
++++ 20.10.8.sh	2021-11-24 11:24:59.136974521 +0530
 @@ -21,28 +21,34 @@
  # the script was uploaded (Should only be modified by upload job):
- SCRIPT_COMMIT_SHA="0e685c6ac0bddd7b2ba7bcaaeb519746ad249a29"
+ SCRIPT_COMMIT_SHA="93d2499759296ac1f9c510605fef85052a2c32be"
  
 -# strip "v" prefix if present
 -VERSION="${VERSION#v}"
@@ -88,7 +88,46 @@
  		*)
  			if command_exists lsb_release; then
  				dist_version="$(lsb_release --release | cut -f2)"
-@@ -448,16 +472,18 @@
+@@ -400,7 +424,7 @@
+ 				fi
+ 				$sh_c 'apt-get update -qq >/dev/null'
+ 				$sh_c "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq $pre_reqs >/dev/null"
+-				$sh_c "curl -fsSL \"$DOWNLOAD_URL/linux/$lsb_dist/gpg\" | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg"
++				$sh_c "curl -fsSL \"$DOWNLOAD_URL/linux/$lsb_dist/gpg\" | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
+ 				$sh_c "echo \"$apt_repo\" > /etc/apt/sources.list.d/docker.list"
+ 				$sh_c 'apt-get update -qq >/dev/null'
+ 			)
+@@ -419,7 +443,28 @@
+ 						echo
+ 						echo "ERROR: '$VERSION' not found amongst apt-cache madison results"
+ 						echo
+-						exit 1
++						echo "Trying to install a lower version of Docker."
++						current_version=$VERSION
++						while :
++						do
++							lower_version=$(echo $current_version | awk -F. '{$NF = $NF - 1;} 1' | sed 's/ /./g')
++							echo "Installing Docker $lower_version ..."
++							$sh_c "curl https://releases.rancher.com/install-docker/$lower_version.sh | sh"
++							if [ "$(which docker)" ]; then
++								echo "Docker $lower_version installed successfully."
++								break
++							fi
++							current_version=$lower_version
++							if [ "$current_version" == "20.10.2" ]; then
++        						current_version="19.03.16"
++    						fi
++							if [ "$current_version" == "19.03.0" ]; then
++        						current_version="18.09.10"
++    						fi
++							if [ "$current_version" == "18.09.1" ]; then
++        						break
++    						fi
++						done
+ 					fi
+ 					if version_gte "18.09"; then
+ 							search_command="apt-cache madison 'docker-ce-cli' | grep '$pkg_pattern' | head -1 | awk '{\$1=\$1};1' | cut -d' ' -f 3"
+@@ -448,16 +493,18 @@
  					# Install docker-ce-rootless-extras without "--no-install-recommends", so as to install slirp4netns when available
  					$sh_c "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce-rootless-extras${pkg_version%=} >/dev/null"
  				fi
@@ -109,7 +148,7 @@
  			if ! curl -Ifs "$yum_repo" > /dev/null; then
  				echo "Error: Unable to curl repository file $yum_repo, is it valid?"
  				exit 1
-@@ -488,6 +514,25 @@
+@@ -488,6 +535,25 @@
  					$sh_c "$config_manager $disable_channel_flag docker-ce-*"
  					$sh_c "$config_manager $enable_channel_flag docker-ce-$CHANNEL"
  				fi
@@ -135,7 +174,79 @@
  				$sh_c "$pkg_manager makecache"
  			)
  			pkg_version=""
-@@ -600,10 +645,25 @@
+@@ -504,7 +570,28 @@
+ 						echo
+ 						echo "ERROR: '$VERSION' not found amongst $pkg_manager list results"
+ 						echo
+-						exit 1
++						echo "Trying to install a lower version of Docker."
++						current_version=$VERSION
++						while :
++						do
++							lower_version=$(echo $current_version | awk -F. '{$NF = $NF - 1;} 1' | sed 's/ /./g')
++							echo "Installing Docker $lower_version ..."
++							$sh_c "curl https://releases.rancher.com/install-docker/$lower_version.sh | sh"
++							if [ "$(which docker)" ]; then
++								echo "Docker $lower_version installed successfully."
++								break
++							fi
++							current_version=$lower_version
++							if [ "$current_version" == "20.10.2" ]; then
++        						current_version="19.03.16"
++    						fi
++							if [ "$current_version" == "19.03.0" ]; then
++        						current_version="18.09.10"
++    						fi
++							if [ "$current_version" == "18.09.1" ]; then
++        						break
++    						fi
++						done
+ 					fi
+ 					if version_gte "18.09"; then
+ 						# older versions don't support a cli package
+@@ -536,10 +623,8 @@
+ 				echo "Packages for SLES are currently only available for s390x"
+ 				exit 1
+ 			fi
+-
+-			sles_version="${dist_version##*.}"
+ 			sles_repo="$DOWNLOAD_URL/linux/$lsb_dist/$REPO_FILE"
+-			opensuse_repo="https://download.opensuse.org/repositories/security:SELinux/SLE_15_SP$sles_version/security:SELinux.repo"
++			opensuse_repo="https://download.opensuse.org/repositories/security:SELinux/SLE_15_SP2/security:SELinux.repo"
+ 			if ! curl -Ifs "$sles_repo" > /dev/null; then
+ 				echo "Error: Unable to curl repository file $sles_repo, is it valid?"
+ 				exit 1
+@@ -578,7 +663,28 @@
+ 						echo
+ 						echo "ERROR: '$VERSION' not found amongst zypper list results"
+ 						echo
+-						exit 1
++						echo "Trying to install a lower version of Docker."
++						current_version=$VERSION
++						while :
++						do
++							lower_version=$(echo $current_version | awk -F. '{$NF = $NF - 1;} 1' | sed 's/ /./g')
++							echo "Installing Docker $lower_version ..."
++							$sh_c "curl https://releases.rancher.com/install-docker/$lower_version.sh | sh"
++							if [ "$(which docker)" ]; then
++								echo "Docker $lower_version installed successfully."
++								break
++							fi
++							current_version=$lower_version
++							if [ "$current_version" == "20.10.2" ]; then
++        						current_version="19.03.16"
++    						fi
++							if [ "$current_version" == "19.03.0" ]; then
++        						current_version="18.09.10"
++    						fi
++							if [ "$current_version" == "18.09.1" ]; then
++        						break
++    						fi
++						done
+ 					fi
+ 					search_command="zypper search -s --match-exact 'docker-ce-cli' | grep '$pkg_pattern' | tail -1 | awk '{print \$6}'"
+ 					# It's okay for cli_pkg_version to be blank, since older versions don't support a cli package
+@@ -602,10 +708,25 @@
  				if version_gte "20.10"; then
  					$sh_c "zypper install -y docker-ce-rootless-extras$rootless_pkg_version"
  				fi
